//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.Src.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Backend.Src.Resources.ValidationErrorMessages", typeof(ValidationErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        public static string A {
            get {
                return ResourceManager.GetString("A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AB.
        /// </summary>
        public static string Ab {
            get {
                return ResourceManager.GetString("Ab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Няма имейл с този имейл. Моля, проверете имейла, който сте предоставили..
        /// </summary>
        public static string AccounNotExistBGBG {
            get {
                return ResourceManager.GetString("AccounNotExistBGBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no account with that email. Please check the email that you provided..
        /// </summary>
        public static string AccounNotExistENUS {
            get {
                return ResourceManager.GetString("AccounNotExistENUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Немає облікового запису з цим електронним адресом. Перевірте вказану вами електронну адресу.
        /// </summary>
        public static string AccounNotExistUKUA {
            get {
                return ResourceManager.GetString("AccounNotExistUKUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Терапия за възрастни.
        /// </summary>
        public static string AdultBGBG {
            get {
                return ResourceManager.GetString("AdultBGBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adult.
        /// </summary>
        public static string AdultENUS {
            get {
                return ResourceManager.GetString("AdultENUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дорослі.
        /// </summary>
        public static string AdultUKUA {
            get {
                return ResourceManager.GetString("AdultUKUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Алергии.
        /// </summary>
        public static string AllergiesBGBG {
            get {
                return ResourceManager.GetString("AllergiesBGBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allergies.
        /// </summary>
        public static string AllergiesENUS {
            get {
                return ResourceManager.GetString("AllergiesENUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Алергія.
        /// </summary>
        public static string AllergiesUKUA {
            get {
                return ResourceManager.GetString("AllergiesUKUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Американски индианец или индианец от Аляска.
        /// </summary>
        public static string AmericanIndianOrAlaskaNativeBGBG {
            get {
                return ResourceManager.GetString("AmericanIndianOrAlaskaNativeBGBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to American Indian or Alaska Native.
        /// </summary>
        public static string AmericanIndianOrAlaskaNativeENUS {
            get {
                return ResourceManager.GetString("AmericanIndianOrAlaskaNativeENUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Корінні народи Америки та Аляски.
        /// </summary>
        public static string AmericanIndianOrAlaskaNativeUKUA {
            get {
                return ResourceManager.GetString("AmericanIndianOrAlaskaNativeUKUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApiModelValidation.
        /// </summary>
        public static string ApiModelValidation {
            get {
                return ResourceManager.GetString("ApiModelValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Азиатски (монголоиден).
        /// </summary>
        public static string AsianBGBG {
            get {
                return ResourceManager.GetString("AsianBGBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asian.
        /// </summary>
        public static string AsianENUS {
            get {
                return ResourceManager.GetString("AsianENUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Азіатський.
        /// </summary>
        public static string AsianUKUA {
            get {
                return ResourceManager.GetString("AsianUKUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        public static string B {
            get {
                return ResourceManager.GetString("B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Information.
        /// </summary>
        public static string BasicInformationENUS {
            get {
                return ResourceManager.GetString("BasicInformationENUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загальна інформація.
        /// </summary>
        public static string BasicInformationUKUA {
            get {
                return ResourceManager.GetString("BasicInformationUKUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Черноафрикански (негроиден).
        /// </summary>
        public static string BlackAfricanBGBG {
            get {
                return ResourceManager.GetString("BlackAfricanBGBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black African.
        /// </summary>
        public static string BlackAfricanENUS {
            get {
                return ResourceManager.GetString("BlackAfricanENUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Народи країн Африки.
        /// </summary>
        public static string BlackAfricanUKUA {
            get {
                return ResourceManager.GetString("BlackAfricanUKUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Черен от Карибския басейн.
        /// </summary>
        public static string BlackCaribbeanBGBG {
            get {
                return ResourceManager.GetString("BlackCaribbeanBGBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black Caribbean.
        /// </summary>
        public static string BlackCaribbeanENUS {
            get {
                return ResourceManager.GetString("BlackCaribbeanENUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Народи островів Карибського моря.
        /// </summary>
        public static string BlackCaribbeanUKUA {
            get {
                return ResourceManager.GetString("BlackCaribbeanUKUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кръв.
        /// </summary>
        public static string BloodBGBG {
            get {
                return ResourceManager.GetString("BloodBGBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood.
        /// </summary>
        public static string BloodENUS {
            get {
                return ResourceManager.GetString("BloodENUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кров.
        /// </summary>
        public static string BloodUKUA {
            get {
                return ResourceManager.GetString("BloodUKUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рак.
        /// </summary>
        public static string CancerBGBG {
            get {
                return ResourceManager.GetString("CancerBGBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancer.
        /// </summary>
        public static string CancerENUS {
            get {
                return ResourceManager.GetString("CancerENUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рак.
        /// </summary>
        public static string CancerUKUA {
            get {
                return ResourceManager.GetString("CancerUKUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Терапия за деца.
        /// </summary>
        public static string ChildhoodBGBG {
            get {
                return ResourceManager.GetString("ChildhoodBGBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Childhood.
        /// </summary>
        public static string ChildhoodENUS {
            get {
                return ResourceManager.GetString("ChildhoodENUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дитячі.
        /// </summary>
        public static string ChildhoodUKUA {
            get {
                return ResourceManager.GetString("ChildhoodUKUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConcurrencyUpdate.
        /// </summary>
        public static string ConcurrencyUpdate {
            get {
                return ResourceManager.GetString("ConcurrencyUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Друга.
        /// </summary>
        public static string CustomBGBG {
            get {
                return ResourceManager.GetString("CustomBGBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string CustomENUS {
            get {
                return ResourceManager.GetString("CustomENUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Користувацька.
        /// </summary>
        public static string CustomUKUA {
            get {
                return ResourceManager.GetString("CustomUKUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataConflict.
        /// </summary>
        public static string DataConflict {
            get {
                return ResourceManager.GetString("DataConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Храносмилателна система.
        /// </summary>
        public static string DigestiveSystemBGBG {
            get {
                return ResourceManager.GetString("DigestiveSystemBGBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digestive System.
        /// </summary>
        public static string DigestiveSystemENUS {
            get {
                return ResourceManager.GetString("DigestiveSystemENUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Система травлення.
        /// </summary>
        public static string DigestiveSystemUKUA {
            get {
                return ResourceManager.GetString("DigestiveSystemUKUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email has been already confirmed.
        /// </summary>
        public static string EmailAlreadyConfirmed {
            get {
                return ResourceManager.GetString("EmailAlreadyConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm your email address. We just re-sent the request..
        /// </summary>
        public static string EmailWasNotConfirmedYet {
            get {
                return ResourceManager.GetString("EmailWasNotConfirmedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ендокринна система.
        /// </summary>
        public static string EndocrineBGBG {
            get {
                return ResourceManager.GetString("EndocrineBGBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endocrine.
        /// </summary>
        public static string EndocrineENUS {
            get {
                return ResourceManager.GetString("EndocrineENUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ендокринна.
        /// </summary>
        public static string EndocrineUKUA {
            get {
                return ResourceManager.GetString("EndocrineUKUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} {1} does not exist..
        /// </summary>
        public static string EntityNotExists {
            get {
                return ResourceManager.GetString("EntityNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EntityNotFound.
        /// </summary>
        public static string EntityNotFound {
            get {
                return ResourceManager.GetString("EntityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EntityValidationError.
        /// </summary>
        public static string EntityValidationError {
            get {
                return ResourceManager.GetString("EntityValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всеки ден.
        /// </summary>
        public static string EveryDayWithAndWithoutMealBGBG {
            get {
                return ResourceManager.GetString("EveryDayWithAndWithoutMealBGBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every day with and without meal.
        /// </summary>
        public static string EveryDayWithAndWithoutMealENUS {
            get {
                return ResourceManager.GetString("EveryDayWithAndWithoutMealENUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кожного дня з їжею та без.
        /// </summary>
        public static string EveryDayWithAndWithoutMealUKUA {
            get {
                return ResourceManager.GetString("EveryDayWithAndWithoutMealUKUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FailedToConnect.
        /// </summary>
        public static string FailedToConnect {
            get {
                return ResourceManager.GetString("FailedToConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Жена.
        /// </summary>
        public static string FemaleBGBG {
            get {
                return ResourceManager.GetString("FemaleBGBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string FemaleENUS {
            get {
                return ResourceManager.GetString("FemaleENUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Женска репродуктивна система.
        /// </summary>
        public static string FemaleReproductiveSystemBGBG {
            get {
                return ResourceManager.GetString("FemaleReproductiveSystemBGBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female Reproductive System.
        /// </summary>
        public static string FemaleReproductiveSystemENUS {
            get {
                return ResourceManager.GetString("FemaleReproductiveSystemENUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Жіноча репродуктивна система.
        /// </summary>
        public static string FemaleReproductiveSystemUKUA {
            get {
                return ResourceManager.GetString("FemaleReproductiveSystemUKUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Жіноча.
        /// </summary>
        public static string FemaleUKUA {
            get {
                return ResourceManager.GetString("FemaleUKUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общи заболявания.
        /// </summary>
        public static string GeneralBGBG {
            get {
                return ResourceManager.GetString("GeneralBGBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string GeneralENUS {
            get {
                return ResourceManager.GetString("GeneralENUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загальні.
        /// </summary>
        public static string GeneralUKUA {
            get {
                return ResourceManager.GetString("GeneralUKUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Генетични.
        /// </summary>
        public static string GeneticBGBG {
            get {
                return ResourceManager.GetString("GeneticBGBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genetic .
        /// </summary>
        public static string GeneticENUS {
            get {
                return ResourceManager.GetString("GeneticENUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Генетика.
        /// </summary>
        public static string GeneticUKUA {
            get {
                return ResourceManager.GetString("GeneticUKUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уши, нос, очи.
        /// </summary>
        public static string HeadBGBG {
            get {
                return ResourceManager.GetString("HeadBGBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ears, nose,eyes.
        /// </summary>
        public static string HeadENUS {
            get {
                return ResourceManager.GetString("HeadENUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вуха, ніс, очі.
        /// </summary>
        public static string HeadUKUA {
            get {
                return ResourceManager.GetString("HeadUKUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cърце.
        /// </summary>
        public static string HeartBGBG {
            get {
                return ResourceManager.GetString("HeartBGBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heart.
        /// </summary>
        public static string HeartENUS {
            get {
                return ResourceManager.GetString("HeartENUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Серце.
        /// </summary>
        public static string HeartUKUA {
            get {
                return ResourceManager.GetString("HeartUKUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всеки ден (високи дози).
        /// </summary>
        public static string HighDosageOfAlсoholDailyBGBG {
            get {
                return ResourceManager.GetString("HighDosageOfAlсoholDailyBGBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High dosage of alсohol daily.
        /// </summary>
        public static string HighDosageOfAlсoholDailyENUS {
            get {
                return ResourceManager.GetString("HighDosageOfAlсoholDailyENUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Велика доза алкоголю щодня.
        /// </summary>
        public static string HighDosageOfAlсoholDailyUKUA {
            get {
                return ResourceManager.GetString("HighDosageOfAlсoholDailyUKUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Латиноамерикански.
        /// </summary>
        public static string HispanicOrLatinoBGBG {
            get {
                return ResourceManager.GetString("HispanicOrLatinoBGBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hispanic or Latino.
        /// </summary>
        public static string HispanicOrLatinoENUS {
            get {
                return ResourceManager.GetString("HispanicOrLatinoENUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Латиноамериканці.
        /// </summary>
        public static string HispanicOrLatinoUKUA {
            get {
                return ResourceManager.GetString("HispanicOrLatinoUKUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HttpsRequired.
        /// </summary>
        public static string HttpsRequired {
            get {
                return ResourceManager.GetString("HttpsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Индийски.
        /// </summary>
        public static string IndianBGBG {
            get {
                return ResourceManager.GetString("IndianBGBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indian.
        /// </summary>
        public static string IndianENUS {
            get {
                return ResourceManager.GetString("IndianENUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Індійська.
        /// </summary>
        public static string IndianUKUA {
            get {
                return ResourceManager.GetString("IndianUKUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повече от 5 часа / седмица.
        /// </summary>
        public static string IntensivelyBGBG {
            get {
                return ResourceManager.GetString("IntensivelyBGBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than 5 hours/week.
        /// </summary>
        public static string IntensivelyENUS {
            get {
                return ResourceManager.GetString("IntensivelyENUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Більше ніж 5 год/тиждень.
        /// </summary>
        public static string IntensivelyUKUA {
            get {
                return ResourceManager.GetString("IntensivelyUKUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Интерсекс.
        /// </summary>
        public static string IntersexBGBG {
            get {
                return ResourceManager.GetString("IntersexBGBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intersex.
        /// </summary>
        public static string IntersexENUS {
            get {
                return ResourceManager.GetString("IntersexENUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Інтерсексуальна.
        /// </summary>
        public static string IntersexUKUA {
            get {
                return ResourceManager.GetString("IntersexUKUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стави и кости.
        /// </summary>
        public static string JointsBonesBGBG {
            get {
                return ResourceManager.GetString("JointsBonesBGBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joints &amp; bones.
        /// </summary>
        public static string JointsBonesENUS {
            get {
                return ResourceManager.GetString("JointsBonesENUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Суглоби та кістки.
        /// </summary>
        public static string JointsBonesUKUA {
            get {
                return ResourceManager.GetString("JointsBonesUKUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; 10 цигари / ден.
        /// </summary>
        public static string LessTenPerDayBGBG {
            get {
                return ResourceManager.GetString("LessTenPerDayBGBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; 10 / day.
        /// </summary>
        public static string LessTenPerDayENUS {
            get {
                return ResourceManager.GetString("LessTenPerDayENUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; 10 / день.
        /// </summary>
        public static string LessTenPerDayUKUA {
            get {
                return ResourceManager.GetString("LessTenPerDayUKUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lifestyle.
        /// </summary>
        public static string LifestyleENUS {
            get {
                return ResourceManager.GetString("LifestyleENUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стиль життя.
        /// </summary>
        public static string LifestyleUKUA {
            get {
                return ResourceManager.GetString("LifestyleUKUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Черен дроб.
        /// </summary>
        public static string LiverBGBG {
            get {
                return ResourceManager.GetString("LiverBGBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liver.
        /// </summary>
        public static string LiverENUS {
            get {
                return ResourceManager.GetString("LiverENUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Печінка.
        /// </summary>
        public static string LiverUKUA {
            get {
                return ResourceManager.GetString("LiverUKUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дългосрочна терапия.
        /// </summary>
        public static string LongTermTherapyBGBG {
            get {
                return ResourceManager.GetString("LongTermTherapyBGBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long Term Therapy.
        /// </summary>
        public static string LongTermTherapyENUS {
            get {
                return ResourceManager.GetString("LongTermTherapyENUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Довготривала терапія.
        /// </summary>
        public static string LongTermTherapyUKUA {
            get {
                return ResourceManager.GetString("LongTermTherapyUKUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По-малко от 1.5 часа / седмица.
        /// </summary>
        public static string LowIntensityBGBG {
            get {
                return ResourceManager.GetString("LowIntensityBGBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less than 1.5 hours/week.
        /// </summary>
        public static string LowIntensityENUS {
            get {
                return ResourceManager.GetString("LowIntensityENUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Менше ніж 1.5 год/тиждень.
        /// </summary>
        public static string LowIntensityUKUA {
            get {
                return ResourceManager.GetString("LowIntensityUKUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бял дроб.
        /// </summary>
        public static string LungBGBG {
            get {
                return ResourceManager.GetString("LungBGBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lung.
        /// </summary>
        public static string LungENUS {
            get {
                return ResourceManager.GetString("LungENUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Легені.
        /// </summary>
        public static string LungUKUA {
            get {
                return ResourceManager.GetString("LungUKUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мъж.
        /// </summary>
        public static string MaleBGBG {
            get {
                return ResourceManager.GetString("MaleBGBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string MaleENUS {
            get {
                return ResourceManager.GetString("MaleENUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мъжка репродуктивна система.
        /// </summary>
        public static string MaleReproductiveBGBG {
            get {
                return ResourceManager.GetString("MaleReproductiveBGBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male reproductive.
        /// </summary>
        public static string MaleReproductiveENUS {
            get {
                return ResourceManager.GetString("MaleReproductiveENUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чоловічий репродуктивна .
        /// </summary>
        public static string MaleReproductiveUKUA {
            get {
                return ResourceManager.GetString("MaleReproductiveUKUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чоловіча.
        /// </summary>
        public static string MaleUKUA {
            get {
                return ResourceManager.GetString("MaleUKUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Метаболични.
        /// </summary>
        public static string MetabolicBGBG {
            get {
                return ResourceManager.GetString("MetabolicBGBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metabolic.
        /// </summary>
        public static string MetabolicENUS {
            get {
                return ResourceManager.GetString("MetabolicENUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Метаболічні.
        /// </summary>
        public static string MetabolicUKUA {
            get {
                return ResourceManager.GetString("MetabolicUKUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Средноизточен.
        /// </summary>
        public static string MiddleEasternBGBG {
            get {
                return ResourceManager.GetString("MiddleEasternBGBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Eastern.
        /// </summary>
        public static string MiddleEasternENUS {
            get {
                return ResourceManager.GetString("MiddleEasternENUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Народи країн Середнього Сходу.
        /// </summary>
        public static string MiddleEasternUKUA {
            get {
                return ResourceManager.GetString("MiddleEasternUKUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.5 до 5 часа / седмица.
        /// </summary>
        public static string ModeratelyBGBG {
            get {
                return ResourceManager.GetString("ModeratelyBGBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.5-5 hours/week.
        /// </summary>
        public static string ModeratelyENUS {
            get {
                return ResourceManager.GetString("ModeratelyENUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.5-5 год/тиждень.
        /// </summary>
        public static string ModeratelyUKUA {
            get {
                return ResourceManager.GetString("ModeratelyUKUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt; 10 цигари / ден.
        /// </summary>
        public static string MoreTenPerDayBGBG {
            get {
                return ResourceManager.GetString("MoreTenPerDayBGBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt; 10 / day.
        /// </summary>
        public static string MoreTenPerDayENUS {
            get {
                return ResourceManager.GetString("MoreTenPerDayENUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt; 10 / день.
        /// </summary>
        public static string MoreTenPerDayUKUA {
            get {
                return ResourceManager.GetString("MoreTenPerDayUKUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хавайски или полинезийски.
        /// </summary>
        public static string NativeHawaiianOrPacificIslanderBGBG {
            get {
                return ResourceManager.GetString("NativeHawaiianOrPacificIslanderBGBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Native Hawaiian or Pacific Islander.
        /// </summary>
        public static string NativeHawaiianOrPacificIslanderENUS {
            get {
                return ResourceManager.GetString("NativeHawaiianOrPacificIslanderENUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гавайці.
        /// </summary>
        public static string NativeHawaiianOrPacificIslanderUKUA {
            get {
                return ResourceManager.GetString("NativeHawaiianOrPacificIslanderUKUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Негативен (-).
        /// </summary>
        public static string NegativeBGBG {
            get {
                return ResourceManager.GetString("NegativeBGBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negative (-).
        /// </summary>
        public static string NegativeENUS {
            get {
                return ResourceManager.GetString("NegativeENUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Негативна (-).
        /// </summary>
        public static string NegativeUKUA {
            get {
                return ResourceManager.GetString("NegativeUKUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нервна система.
        /// </summary>
        public static string NervousSystemPsychologicalBGBG {
            get {
                return ResourceManager.GetString("NervousSystemPsychologicalBGBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nervous System &amp; Psychological.
        /// </summary>
        public static string NervousSystemPsychologicalENUS {
            get {
                return ResourceManager.GetString("NervousSystemPsychologicalENUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нервова система та психологія.
        /// </summary>
        public static string NervousSystemPsychologicalUKUA {
            get {
                return ResourceManager.GetString("NervousSystemPsychologicalUKUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to He.
        /// </summary>
        public static string NoBGBG {
            get {
                return ResourceManager.GetString("NoBGBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string NoENUS {
            get {
                return ResourceManager.GetString("NoENUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нормална диета.
        /// </summary>
        public static string NormalBGBG {
            get {
                return ResourceManager.GetString("NormalBGBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string NormalENUS {
            get {
                return ResourceManager.GetString("NormalENUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Звичайна.
        /// </summary>
        public static string NormalUKUA {
            get {
                return ResourceManager.GetString("NormalUKUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ні.
        /// </summary>
        public static string NoUKUA {
            get {
                return ResourceManager.GetString("NoUKUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O.
        /// </summary>
        public static string O {
            get {
                return ResourceManager.GetString("O", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Понякога по време на хранене.
        /// </summary>
        public static string OccasionallyWithMealsBGBG {
            get {
                return ResourceManager.GetString("OccasionallyWithMealsBGBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occasionally with meals.
        /// </summary>
        public static string OccasionallyWithMealsENUS {
            get {
                return ResourceManager.GetString("OccasionallyWithMealsENUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Іноді з їжею.
        /// </summary>
        public static string OccasionallyWithMealsUKUA {
            get {
                return ResourceManager.GetString("OccasionallyWithMealsUKUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Друг.
        /// </summary>
        public static string OtherBGBG {
            get {
                return ResourceManager.GetString("OtherBGBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Други заболявания.
        /// </summary>
        public static string OtherConditionsBGBG {
            get {
                return ResourceManager.GetString("OtherConditionsBGBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other conditions.
        /// </summary>
        public static string OtherConditionsENUS {
            get {
                return ResourceManager.GetString("OtherConditionsENUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Інші захворювання.
        /// </summary>
        public static string OtherConditionsUKUA {
            get {
                return ResourceManager.GetString("OtherConditionsUKUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string OtherENUS {
            get {
                return ResourceManager.GetString("OtherENUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Інше.
        /// </summary>
        public static string OtherUKUA {
            get {
                return ResourceManager.GetString("OtherUKUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бивш пушач.
        /// </summary>
        public static string PastSmokerBGBG {
            get {
                return ResourceManager.GetString("PastSmokerBGBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Past smoker.
        /// </summary>
        public static string PastSmokerENUS {
            get {
                return ResourceManager.GetString("PastSmokerENUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Колишній курець.
        /// </summary>
        public static string PastSmokerUKUA {
            get {
                return ResourceManager.GetString("PastSmokerUKUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PermissionDenied.
        /// </summary>
        public static string PermissionDenied {
            get {
                return ResourceManager.GetString("PermissionDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лула.
        /// </summary>
        public static string PipeBGBG {
            get {
                return ResourceManager.GetString("PipeBGBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pipe.
        /// </summary>
        public static string PipeENUS {
            get {
                return ResourceManager.GetString("PipeENUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Люлька.
        /// </summary>
        public static string PipeUKUA {
            get {
                return ResourceManager.GetString("PipeUKUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Положителен (+).
        /// </summary>
        public static string PositiveBGBG {
            get {
                return ResourceManager.GetString("PositiveBGBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positive (+).
        /// </summary>
        public static string PositiveENUS {
            get {
                return ResourceManager.GetString("PositiveENUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Позитивна (+).
        /// </summary>
        public static string PositiveUKUA {
            get {
                return ResourceManager.GetString("PositiveUKUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Психични разстройства.
        /// </summary>
        public static string PsychiatricDisordersBGBG {
            get {
                return ResourceManager.GetString("PsychiatricDisordersBGBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Psychiatric disorders.
        /// </summary>
        public static string PsychiatricDisordersENUS {
            get {
                return ResourceManager.GetString("PsychiatricDisordersENUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Психічні розлади.
        /// </summary>
        public static string PsychiatricDisordersUKUA {
            get {
                return ResourceManager.GetString("PsychiatricDisordersUKUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequestBodyNotFound.
        /// </summary>
        public static string RequestBodyNotFound {
            get {
                return ResourceManager.GetString("RequestBodyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceWasNotInitialized.
        /// </summary>
        public static string ServiceWasNotInitialized {
            get {
                return ResourceManager.GetString("ServiceWasNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кожни и автоимунни.
        /// </summary>
        public static string SkinAutoimmuneBGBG {
            get {
                return ResourceManager.GetString("SkinAutoimmuneBGBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skin &amp; Autoimmune.
        /// </summary>
        public static string SkinAutoimmuneENUS {
            get {
                return ResourceManager.GetString("SkinAutoimmuneENUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шкіра та аутоімунні.
        /// </summary>
        public static string SkinAutoimmuneUKUA {
            get {
                return ResourceManager.GetString("SkinAutoimmuneUKUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Трансплантации.
        /// </summary>
        public static string TransplantBGBG {
            get {
                return ResourceManager.GetString("TransplantBGBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transplant.
        /// </summary>
        public static string TransplantENUS {
            get {
                return ResourceManager.GetString("TransplantENUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пересадка.
        /// </summary>
        public static string TransplantUKUA {
            get {
                return ResourceManager.GetString("TransplantUKUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пикочна система.
        /// </summary>
        public static string UrinarySystemBGBG {
            get {
                return ResourceManager.GetString("UrinarySystemBGBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urinary system.
        /// </summary>
        public static string UrinarySystemENUS {
            get {
                return ResourceManager.GetString("UrinarySystemENUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сечовидільна система.
        /// </summary>
        public static string UrinarySystemUKUA {
            get {
                return ResourceManager.GetString("UrinarySystemUKUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with email &apos;{0}&apos; has been already registered..
        /// </summary>
        public static string UserEmailExists {
            get {
                return ResourceManager.GetString("UserEmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} does not belong to Person {1}.
        /// </summary>
        public static string UserNotBelongToCompany {
            get {
                return ResourceManager.GetString("UserNotBelongToCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Веганство.
        /// </summary>
        public static string VeganBGBG {
            get {
                return ResourceManager.GetString("VeganBGBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vegan.
        /// </summary>
        public static string VeganENUS {
            get {
                return ResourceManager.GetString("VeganENUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Веганський.
        /// </summary>
        public static string VeganUKUA {
            get {
                return ResourceManager.GetString("VeganUKUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вегетарианство.
        /// </summary>
        public static string VegetarianBGBG {
            get {
                return ResourceManager.GetString("VegetarianBGBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vegetarian.
        /// </summary>
        public static string VegetarianENUS {
            get {
                return ResourceManager.GetString("VegetarianENUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вегетаріанський.
        /// </summary>
        public static string VegetarianUKUA {
            get {
                return ResourceManager.GetString("VegetarianUKUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бял (европеиден).
        /// </summary>
        public static string WhiteOrCaucasianBGBG {
            get {
                return ResourceManager.GetString("WhiteOrCaucasianBGBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White or Caucasian.
        /// </summary>
        public static string WhiteOrCaucasianENUS {
            get {
                return ResourceManager.GetString("WhiteOrCaucasianENUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вихідці з країн Європи.
        /// </summary>
        public static string WhiteOrCaucasianUKUA {
            get {
                return ResourceManager.GetString("WhiteOrCaucasianUKUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to С всяко хранене.
        /// </summary>
        public static string WithEveryMealBGBG {
            get {
                return ResourceManager.GetString("WithEveryMealBGBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Every Meal.
        /// </summary>
        public static string WithEveryMealENUS {
            get {
                return ResourceManager.GetString("WithEveryMealENUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to З кожним харчуванням.
        /// </summary>
        public static string WithEveryMealUKUA {
            get {
                return ResourceManager.GetString("WithEveryMealUKUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong email or password..
        /// </summary>
        public static string WrongLoginInfo {
            get {
                return ResourceManager.GetString("WrongLoginInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WrongSortedFieldName.
        /// </summary>
        public static string WrongSortedFieldName {
            get {
                return ResourceManager.GetString("WrongSortedFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to да.
        /// </summary>
        public static string YesBGBG {
            get {
                return ResourceManager.GetString("YesBGBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yes.
        /// </summary>
        public static string YesEN {
            get {
                return ResourceManager.GetString("YesEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yes.
        /// </summary>
        public static string YesENUS {
            get {
                return ResourceManager.GetString("YesENUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to так.
        /// </summary>
        public static string YesUKUA {
            get {
                return ResourceManager.GetString("YesUKUA", resourceCulture);
            }
        }
    }
}
